Repository bcgov/jag-dps, pull requests merged in 2020-01, with the labels that each got.

#68 Feature/template testing
  .github/cicd/functions.sh
  .github/cicd/player.sh
  Jenkinsfile
Labels: ci/cd pipeline

#73 added deploy config for sonarqube
  openshift/templates/sonarqube.dc.yaml
Labels: ci/cd pipeline

#79 jenkinsfile updated for quality checks
  Jenkinsfile
Labels: ci/cd pipeline

#83 Fix pipeline paths
  .github/cicd/player.sh
  configurations/fig-validation-service.conf
Labels: ci/cd pipeline

#89 Jenkins - Part 2
  .github/cicd/functions.sh
  .github/cicd/player.sh
  configurations/fig-validation-service.conf
  configurations/project.conf
  openshift/templates/dps-payment-service.bc.yaml
  openshift/templates/dps-payment-service.dc.yaml
  openshift/templates/dps-validation-service.bc.yaml
  openshift/templates/dps-validation-service.dc.yaml
  openshift/templates/fig-validation-service.bc.yaml
  openshift/templates/fig-validation-service.dc.yaml
Labels: bug, ci/cd pipeline, dependencies

#71 added abstracted dockerfiles per service
  openshift/dockerfiles/dpsvalidation-docker-compose.yml
  openshift/dockerfiles/figvalidation-docker-compose.yml
  openshift/dockerfiles/paymentservice-docker-compose.yml
Labels: ci/cd pipeline

#105 Changing references to use toolspace as central repo
  openshift/templates/fig-validation-service.bc.yaml
  src/openshift.dockerfile
Labels: ci/cd pipeline, dependencies

#107 added sanitized master pipeline
  openshift/pipelines/pipeline-build-template.yaml
Labels: ci/cd pipeline, documentation
